In [1]:
# Enabling reloading extension to use external python files
%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np
import os.path
import os
import columns
import datasets
import seasons
import directory_utils

In [3]:
data_dict = {sheet_name: [] for sheet_name in datasets.SHEETS_NAMES}
data_dict

{'111': [], '222': [], '333': [], '265': []}

In [4]:
def read_sheet_as_data_frame(xls, sheet_name):
    sheet = pd.read_excel(xls, sheet_name=sheet_name)
    
    columns_to_drop = []
    for column in sheet.columns:
        if(columns.UNNAMED in column):
            columns_to_drop.append(column)
    df = sheet.drop(columns_to_drop, axis=1) 
    
    return df

In [5]:
spreadsheet_names = [str(1997+w) for w in range(0,20)]

for name in spreadsheet_names:
    file_path = datasets.ORIGINAL_DATA_SETS_PATH + "/" + name + ".xlsx"
    
    if os.path.isfile(file_path):
        with pd.ExcelFile(file_path) as xls:          
            for sheet_name in datasets.SHEETS_NAMES:
                if sheet_name in xls.sheet_names:
                    df = read_sheet_as_data_frame(xls,sheet_name)
                    data_dict[sheet_name].append(df)

    else:
        print('File "' + file_path + '" was not found.')

In [6]:
data_frames = {sheet_name: pd.concat(data_frames) for sheet_name, data_frames in data_dict.items()}
for name, data_frame in data_frames.items():
    print('Shape of \"' + name + '\":' + str(data_frame.shape))

Shape of "111":(1050445, 18)
Shape of "222":(6914, 21)
Shape of "333":(26001, 10)
Shape of "265":(6864, 13)

In [7]:
directory_utils.create_if_doesnt_exist(datasets.MERGED_CSVS_DIRECTORY_PATH)

for sheet_name, data_frame in data_frames.items():
    csv_output_file_path = datasets.MERGED_CSVS_DIRECTORY_PATH + '/' + sheet_name + '.csv'
    data_frame.to_csv(csv_output_file_path , index = False, encoding=datasets.DEFAULT_CSV_ENCODING)

In [8]:
data_frame_111 = data_frames[datasets.SHEET_111_NAME]
data_frame_222 = data_frames[datasets.SHEET_222_NAME]
data_frame_333 = data_frames[datasets.SHEET_333_NAME]
data_frame_265 = data_frames[datasets.SHEET_265_NAME]

### Analyzing 111 data frame

In [9]:
data_frame_111.head(2)

,Cod,Ano,Dia Juliano,Hora - minuto,Veloc. Instantânea do Vento a 5 metros (m/s),Veloc. Instantânea do Vento a 2 metros (m/s),Direção do Vento no instante da aquisição (°),Radiação Incidente total de 10 leituras (KW/m2),Radiação Refletida Total de 10 leituras (KW/m2),Fluxo Positivo de calor no solo total de 10 leituras (W/m2),Fluxo negativo de calor no solo . total de 10 leituras (W/m2),Umidade relativa Média (%),Temperatura do Ar Média (°C),Temperatura do solo 1 Média (°C) à 3cm no solo,Temperatura do solo 2Média (°C) à 6cm no solo,Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09,Pressão (hPa),Chuva total do período (mm)
0,111,1997,1.0,10,1618.00,1115.000,8.32,0.0,0.0,0.0,-443.0,92.3,19.84,21.04,22.68,24.59,943.0,0
1,111,1997,1.0,20,0.99,0.763,20.59,0.0,0.0,0.0,-443.0,93.1,19.63,20.97,22.65,24.52,943.0,0

In [10]:
data_frame_111.columns

Index(['Cod', 'Ano', 'Dia Juliano', 'Hora - minuto',
       'Veloc. Instantânea do Vento a 5 metros (m/s)',
       'Veloc. Instantânea do Vento a 2 metros (m/s)',
       'Direção do Vento no instante da aquisição (°)',
       'Radiação Incidente total de 10 leituras (KW/m2)',
       'Radiação Refletida Total de 10 leituras (KW/m2)',
       'Fluxo Positivo de calor no solo total de 10 leituras (W/m2)',
       'Fluxo negativo de calor no solo . total de 10 leituras (W/m2)',
       'Umidade relativa Média (%)', 'Temperatura do Ar Média (°C)',
       'Temperatura do solo  1 Média (°C) à 3cm no solo',
       'Temperatura do solo 2Média (°C) à 6cm no solo ',
       'Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09',
       'Pressão (hPa)', 'Chuva total do período (mm)'],
      dtype='object')

In [11]:
data_frame_111.Cod.unique()

array([111, 333, 265, 222])

In [12]:
print(data_frame_111[data_frame_111.Cod != 111][columns.YEAR].unique())

[2005]

In [13]:
data_frame_111.isnull().sum()

Cod                                                                     0
Ano                                                                     0
Dia Juliano                                                             0
Hora - minuto                                                           0
Veloc. Instantânea do Vento a 5 metros (m/s)                            0
Veloc. Instantânea do Vento a 2 metros (m/s)                            0
Direção do Vento no instante da aquisição (°)                           0
Radiação Incidente total de 10 leituras (KW/m2)                         0
Radiação Refletida Total de 10 leituras (KW/m2)                         0
Fluxo Positivo de calor no solo total de 10 leituras (W/m2)             0
Fluxo negativo de calor no solo . total de 10 leituras (W/m2)        1825
Umidade relativa Média (%)                                           1826
Temperatura do Ar Média (°C)                                         1826
Temperatura do solo  1 Média (°C) à 3cm no solo                      2191
Temperatura do solo 2Média (°C) à 6cm no solo                        2191
Temperatura do solo 3Média (°C) Colocado sensor de UV em 31/07/09    2191
Pressão (hPa)                                                        2191
Chuva total do período (mm)                                          2191
dtype: int64

In [14]:
data_frame_111.describe()

,Cod,Ano,Dia Juliano,Hora - minuto,Veloc. Instantânea do Vento a 5 metros (m/s),Veloc. Instantânea do Vento a 2 metros (m/s),Direção do Vento no instante da aquisição (°),Radiação Incidente total de 10 leituras (KW/m2),Radiação Refletida Total de 10 leituras (KW/m2),Fluxo Positivo de calor no solo total de 10 leituras (W/m2),Fluxo negativo de calor no solo . total de 10 leituras (W/m2),Umidade relativa Média (%),Temperatura do Ar Média (°C),Temperatura do solo 1 Média (°C) à 3cm no solo,Temperatura do solo 2Média (°C) à 6cm no solo,Pressão (hPa)
count,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.050445e+06,1.048620e+06,1.048619e+06,1.048619e+06,1.048254e+06,1.048254e+06,1.048254e+06
mean,1.114778e+02,2.006549e+03,1.835618e+02,1.192104e+03,1.472154e+03,9.129840e+02,2.723121e+02,7.622076e+02,2.706437e+02,3.653693e+02,-1.662485e+03,7.404259e+01,2.634531e+01,1.332214e+03,1.296305e+03,9.462274e+02
std,9.895335e+00,5.762457e+00,1.053855e+02,6.927634e+02,1.353874e+03,1.134761e+03,6.693158e+02,1.611430e+03,8.889303e+02,1.147225e+03,2.796438e+03,2.748618e+01,2.413575e+02,2.725003e+03,2.694402e+03,8.089817e+01
min,1.110000e+02,1.997000e+03,-5.336000e+01,1.000000e+01,-6.999000e+03,0.000000e+00,0.000000e+00,-6.999000e+03,0.000000e+00,0.000000e+00,-6.999000e+03,-6.999000e+03,-6.999000e+03,-6.999000e+03,-6.999000e+03,-6.999000e+03
25%,1.110000e+02,2.002000e+03,9.300000e+01,6.100000e+02,1.010000e+00,5.390000e-01,9.380000e+01,0.000000e+00,0.000000e+00,0.000000e+00,-5.298000e+02,6.053000e+01,1.813000e+01,2.049000e+01,2.117000e+01,9.430000e+02
50%,1.110000e+02,2.007000e+03,1.840000e+02,1.210000e+03,1.481000e+03,1.010000e+00,1.555000e+02,0.000000e+00,0.000000e+00,0.000000e+00,-2.460000e+02,7.750000e+01,2.114000e+01,2.448000e+01,2.493000e+01,9.470000e+02
75%,1.110000e+02,2.012000e+03,2.750000e+02,1.810000e+03,2.265000e+03,1.716000e+03,2.576000e+02,4.338000e+02,9.890000e-01,1.788000e+02,0.000000e+00,8.920000e+01,2.510000e+01,3.198000e+01,2.988000e+01,9.520000e+02
max,3.330000e+02,2.139000e+03,6.540000e+02,6.640000e+03,6.996000e+03,6.999000e+03,6.999000e+03,6.999000e+03,6.999000e+03,6.999000e+03,6.538000e+03,6.836000e+03,1.822660e+05,6.999000e+03,6.999000e+03,2.802000e+03

### Analyzing 222 data frame

In [15]:
data_frame_222.head(2)

,Cod,Ano,Dia Juliano,Hora - minuto,Veloc. máxima do Vento a 5 metros (m/s),Veloc. máxima do Vento a 2 metros (m/s),Direção do Vento no instante da veloc. Máx.(°),Horário de ocorrência vr máx. veloc. do vento,Radiação Incidente Total do dia (KW/m2),Radiação Refletida Total do dia (KW/m2),...,Fluxo Negativo de calor no solo. Total do dia (KW/m2),Temperatura do Ar Máxima do dia (°C),Horário de ocorrência da Temp. Ar Máxima(°C),Temperatura do Ar Mínima do dia (°C),Horário de ocorrência da Temp. Ar Minima,Temperatura do Solo 1 Máxima do dia (°C),Horário de ocorrência da Temp. Solo 1 Máxima.,Temperatura do Solo 1 Mínima do dia (°C),Horário de ocorrência da Temp. Solo 1 minima,Chuva total do dia (mm)
0,222,1997,1,2400,6031.0,2677.0,99.6,1923,270.8,53.81,...,-34.76,30.16,1255,18.50,551.0,34.53,1258,19.15,606.0,0.0
1,222,1997,2,2400,4756.0,1758.0,119.5,45,165.3,27.46,...,-26.86,26.15,1417,19.15,2355.0,27.66,1425,19.65,2352.0,0.0

In [16]:
data_frame_222.columns

Index(['Cod', 'Ano', 'Dia Juliano', 'Hora - minuto',
       'Veloc. máxima do Vento a 5 metros (m/s)',
       'Veloc. máxima do Vento a 2 metros (m/s)',
       'Direção do Vento no instante da veloc. Máx.(°)',
       'Horário de ocorrência vr máx. veloc. do vento',
       'Radiação Incidente Total do dia (KW/m2)',
       'Radiação Refletida Total do dia (KW/m2)',
       'Fluxo positivo de calor no solo Total do dia (KW/m2)',
       'Fluxo Negativo de calor no solo. Total do dia (KW/m2)',
       'Temperatura do Ar  Máxima do dia (°C)',
       'Horário de ocorrência da Temp. Ar Máxima(°C)',
       'Temperatura do Ar Mínima do dia (°C)',
       'Horário de ocorrência da Temp. Ar Minima',
       'Temperatura do Solo 1 Máxima do dia (°C)',
       'Horário de ocorrência da Temp. Solo 1 Máxima.',
       'Temperatura do Solo 1 Mínima do dia (°C)',
       'Horário de ocorrência da Temp. Solo 1 minima',
       'Chuva total do dia (mm)'],
      dtype='object')

In [17]:
data_frame_222.Cod.unique()

array([222], dtype=object)

In [18]:
print(data_frame_222[data_frame_222.Cod != 222][columns.YEAR].unique())

[]

In [19]:
data_frame_222.isnull().sum()

Cod                                                        0
Ano                                                        0
Dia Juliano                                                0
Hora - minuto                                              0
Veloc. máxima do Vento a 5 metros (m/s)                    0
Veloc. máxima do Vento a 2 metros (m/s)                    0
Direção do Vento no instante da veloc. Máx.(°)             0
Horário de ocorrência vr máx. veloc. do vento              0
Radiação Incidente Total do dia (KW/m2)                    0
Radiação Refletida Total do dia (KW/m2)                    0
Fluxo positivo de calor no solo Total do dia (KW/m2)       0
Fluxo Negativo de calor no solo. Total do dia (KW/m2)      0
Temperatura do Ar  Máxima do dia (°C)                      1
Horário de ocorrência da Temp. Ar Máxima(°C)               1
Temperatura do Ar Mínima do dia (°C)                       1
Horário de ocorrência da Temp. Ar Minima                   1
Temperatura do Solo 1 Máxima do dia (°C)                   1
Horário de ocorrência da Temp. Solo 1 Máxima.              1
Temperatura do Solo 1 Mínima do dia (°C)                   1
Horário de ocorrência da Temp. Solo 1 minima               2
Chuva total do dia (mm)                                  151
dtype: int64

In [20]:
data_frame_222.describe()

,Veloc. máxima do Vento a 5 metros (m/s),Veloc. máxima do Vento a 2 metros (m/s),Direção do Vento no instante da veloc. Máx.(°),Radiação Incidente Total do dia (KW/m2),Radiação Refletida Total do dia (KW/m2),Fluxo positivo de calor no solo Total do dia (KW/m2),Temperatura do Ar Mínima do dia (°C),Horário de ocorrência da Temp. Ar Minima,Temperatura do Solo 1 Mínima do dia (°C),Horário de ocorrência da Temp. Solo 1 minima,Chuva total do dia (mm)
count,6914.000000,6914.000000,6914.000000,6914.000000,6914.000000,6914.000000,6913.000000,6913.000000,6913.000000,6912.00000,6763.000000
mean,3666.239481,2584.439435,288.337367,210.470264,120.182050,108.991185,51.907359,791.598438,783.914700,783.52474,252.199053
std,2038.105213,1860.333669,625.759617,275.510678,424.527474,716.880089,466.418455,656.412518,2249.099354,611.03749,992.209132
min,0.000000,0.000000,0.000000,0.000000,0.000000,-931.000000,0.000000,0.000000,-6999.000000,0.00000,0.000000
25%,3109.000000,5.090000,131.900000,110.600000,42.647500,-201.700000,14.020000,501.000000,15.480000,559.00000,0.000000
50%,4109.000000,2854.000000,181.100000,207.700000,65.625000,26.230000,16.910000,558.000000,19.770000,649.00000,0.000000
75%,5011.000000,3910.250000,282.600000,274.100000,98.500000,81.275000,19.040000,652.000000,22.910000,732.25000,2.540000
max,6973.000000,6973.000000,6897.000000,6589.000000,6909.000000,6924.000000,6991.000000,2400.000000,6999.000000,2400.00000,6858.000000

### Analyzing 333 data frame

In [21]:
data_frame_333.head(2)

,Cod,Ano,Dia Juliano,Hora - minuto,Veloc. Instantânea do Vento a 5 metros (m/s),Veloc. Instantânea do Vento a 2 metros (m/s),Direção do Vento no instantânea (°),Umidade relativa Instantânea (%),Temperatura do Ar Instantânea (°C),Pressão
0,333,1997,1.0,700,3344.0,1973.0,89.1,89.7,20.47,942
1,333,1997,1.0,900,2618.0,1544.0,185.6,80.2,23.38,944

In [22]:
data_frame_333.columns

Index(['Cod', 'Ano', 'Dia Juliano', 'Hora - minuto',
       'Veloc. Instantânea do Vento a 5 metros (m/s)',
       'Veloc. Instantânea do Vento a 2 metros (m/s)',
       'Direção do Vento no instantânea  (°)',
       'Umidade relativa Instantânea  (%)',
       'Temperatura do Ar Instantânea (°C)', 'Pressão'],
      dtype='object')

In [23]:
data_frame_333.Cod.unique()

array([333], dtype=object)

In [24]:
print(data_frame_333[data_frame_333.Cod != 333][columns.YEAR].unique())

[]

In [25]:
data_frame_333.isnull().sum()

Cod                                             0
Ano                                             0
Dia Juliano                                     0
Hora - minuto                                   0
Veloc. Instantânea do Vento a 5 metros (m/s)    0
Veloc. Instantânea do Vento a 2 metros (m/s)    0
Direção do Vento no instantânea  (°)            0
Umidade relativa Instantânea  (%)               0
Temperatura do Ar Instantânea (°C)              0
Pressão                                         0
dtype: int64

In [26]:
data_frame_333.describe()

,Dia Juliano,Veloc. Instantânea do Vento a 5 metros (m/s),Veloc. Instantânea do Vento a 2 metros (m/s),Direção do Vento no instantânea (°),Umidade relativa Instantânea (%),Temperatura do Ar Instantânea (°C)
count,26001.000000,26001.000000,26001.000000,26001.000000,26001.000000,26001.000000
mean,180.482874,1434.967665,1041.404223,300.222295,69.928546,27.642355
std,105.504686,1268.984601,1124.401471,727.433045,19.715930,173.852086
min,-53.360000,0.000000,0.000000,0.000000,7.770000,-165.200000
25%,89.000000,1.010000,0.763000,96.500000,54.920000,19.140000
50%,179.000000,1481.000000,1167.000000,158.400000,72.300000,22.500000
75%,272.000000,2187.000000,1743.000000,275.000000,85.600000,26.680000
max,366.000000,6895.000000,6679.000000,6952.000000,100.000000,6999.000000

### Analyzing 265 data frame

In [27]:
data_frame_265.head(2)

,Cod,Ano,Dia Juliano,Hora - minuto,Chuva das 7 h as 7 h,Temperatura do Ar máxima do dia °C,Horário de ocorrência da Temp. Ar máxima,Temperatura do Ar Minima do dia (°C),Horário de ocorrência da Temp. Ar minima,Umidade máxima,Hora,Umidade mínima,Hora.1
0,265,1997,1.0,700,0.0,31.11,1356,18.50,551.0,NaN,NaN,NaN,NaN
1,265,1997,2.0,700,0.0,30.16,1255,19.21,510.0,NaN,NaN,NaN,NaN

In [28]:
data_frame_265.columns

Index(['Cod', 'Ano', 'Dia Juliano', 'Hora - minuto', 'Chuva das 7 h as 7 h',
       'Temperatura do Ar máxima do dia °C',
       'Horário de ocorrência da Temp. Ar máxima',
       'Temperatura do Ar Minima do dia (°C)',
       'Horário de ocorrência da Temp. Ar minima', 'Umidade máxima', 'Hora',
       'Umidade mínima', 'Hora.1'],
      dtype='object')

In [29]:
data_frame_265.Cod.unique()

array([265], dtype=object)

In [30]:
print(data_frame_265[data_frame_265.Cod != 265][columns.YEAR].unique())

[]

In [31]:
data_frame_265.isnull().sum()

Cod                                          0
Ano                                          0
Dia Juliano                                  0
Hora - minuto                                0
Chuva das 7 h as 7 h                         0
Temperatura do Ar máxima do dia °C           0
Horário de ocorrência da Temp. Ar máxima     0
Temperatura do Ar Minima do dia (°C)         5
Horário de ocorrência da Temp. Ar minima     5
Umidade máxima                              57
Hora                                        57
Umidade mínima                              57
Hora.1                                      57
dtype: int64

In [32]:
data_frame_265.describe()

,Dia Juliano,Chuva das 7 h as 7 h,Temperatura do Ar máxima do dia °C,Temperatura do Ar Minima do dia (°C),Horário de ocorrência da Temp. Ar minima,Umidade máxima,Hora,Umidade mínima,Hora.1
count,6864.000000,6864.000000,6864.000000,6859.000000,6859.000000,6807.000000,6807.000000,6807.000000,6807.000000
mean,183.431911,259.223644,30.550498,64.955059,600.501385,92.501716,681.093874,47.692695,1427.192596
std,105.584961,1013.569334,119.044092,555.781940,310.560816,7.417340,402.932153,105.982793,245.718799
min,-53.360000,0.000000,11.660000,-6999.000000,-6999.000000,51.080000,1.000000,-6999.000000,-6999.000000
25%,92.000000,0.000000,26.140000,13.780000,509.000000,88.400000,519.000000,37.235000,1346.000000
50%,184.000000,0.000000,28.860000,16.910000,606.000000,94.000000,638.000000,46.550000,1449.000000
75%,275.000000,2.540000,31.380000,19.170000,701.000000,99.100000,702.000000,57.210000,1544.000000
max,366.000000,6999.000000,6999.000000,6991.000000,2400.000000,100.000000,2359.000000,5044.000000,2353.000000